<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite65d319bc9ab13679fb95b0aa5a089f2
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'PAMI\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'PAMI\\' => 
        array (
            0 => __DIR__ . '/..' . '/marcelog/pami/src/PAMI',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite65d319bc9ab13679fb95b0aa5a089f2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite65d319bc9ab13679fb95b0aa5a089f2::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
